CREATE TABLE items (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	item VARCHAR(50) NOT NULL,
	type_id INT UNSIGNED NOT NULL,
	consumable BOOLEAN NOT NULL DEFAULT 0,
	cumulative BOOLEAN NOT NULL DEFAULT 0,
	quest_item BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	CONSTRAINT fk_type_id FOREIGN KEY (type_id) REFERENCES items_types(id)
);

SELECT * FROM items;
DESCRIBE items;
DROP TABLE items;