CREATE TABLE users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	full_name VARCHAR(100) NOT NULL,
	born_date DATE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	user_password TINYTEXT NOT NULL,
	PRIMARY KEY(id)
);

DESCRIBE users;
DROP TABLE users;